name: Cowsay Workflow
on: push
jobs: 
    cowsay:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout
             uses: actions/checkout@v4
           - name: Install Cowsay
             run: sudo apt-get install cowsay -y
           - name: Execute Cowsay
             run: |
                cowsay -l
                cowsay -f dragon "Run for cover, I am DRaGON... RAWR" >> dragon.txt
           - name: List files
             run: ls -ltra
