name: Cowsay Workflow
on:
    push:
        branches: [ main ]
jobs:
    job1:
        name: Generate Message
        runs-on: ubuntu-latest
        outputs:
            message-file: ${{ steps.save-message.outputs.message-file }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate message
              run: echo "Hello from Job 1!" > message.txt

            - name: Save message file path
              id: save-message
              run: echo "message-file=message.txt" >> $GITHUB_OUTPUT

            - name: Upload message artifact
              uses: actions/upload-artifact@v4
              with:
                name: message
                path: message.txt

    job2:
        name: Cowsay Message
        runs-on: ubuntu-latest
        needs: job1
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Download message artifact
            uses: actions/download-artifact@v4
            with:
              name: message

          - name: Install cowsay
            run: sudo apt-get update && sudo apt-get install -y cowsay

          - name: Run cowsay with message
            run: ls && cowsay "$(cat message.txt)" > cowsay.txt

          - name: Upload cowsay artifact
            uses: actions/upload-artifact@v4
            with:
              name: cowsay
              path: cowsay.txt

    job3:
        name: Print Cowsay Output
        runs-on: ubuntu-latest
        needs: job2
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Download cowsay artifact
            uses: actions/download-artifact@v4
            with:
              name: cowsay

          - name: Display cowsay output
            run: cat cowsay.txt