name: my first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Welcome
              run: echo "Welcome"
            - name: list
              run: ls -la